#Appsec Docker Container to practice and test Appsec related skills
FROM debian
MAINTAINER pggsx

ENV DEBIAN_FRONTEND noninteractive

run adduser deploy
run useradd -g deploy sudo
run apt-get -y update && apt-get -y upgrade
#insert project build
run echo "insert git clone here"
run echo "build complete"
